name: Send Email

on:
  workflow_dispatch:
    inputs:
      email:
        description: 'User email'
        required: true

jobs:
  send_email:
    runs-on: ubuntu-22.04
    steps:
    - name: Send email
      env:
        EMAIL: ${{ secrets.EMAIL }}
        EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
      run: |
        echo "User email: ${{ github.event.inputs.email }}"
        echo "Sending email to $EMAIL"

        sudo apt-get update
        sudo apt-get install -y ssmtp
        echo "root=EMAIL@gmail.com" | sudo tee -a /etc/ssmtp/ssmtp.conf
        echo "mailhub=smtp.gmail.com:587" | sudo tee -a /etc/ssmtp/ssmtp.conf
        echo "AuthUser=$EMAIL" | sudo tee -a /etc/ssmtp/ssmtp.conf
        echo "AuthPass=$EMAIL_PASSWORD" | sudo tee -a /etc/ssmtp/ssmtp.conf
        echo "UseSTARTTLS=YES" | sudo tee -a /etc/ssmtp/ssmtp.conf

        echo "Thank you for joining our waiting list!" | ssmtp -vvv ${{ github.event.inputs.email }}
